name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install MkDocs and dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-material  # Add this if you're using the Material theme

    - name: Deploy to GitHub Pages
      run: mkdocs gh-deploy --force
